In [35]:
import numpy as np
import pandas as pd
import os,sys
#reading positive and negative csv files into dataframe
pos_input_file = os.path.join('pos_feat_vec.csv')
neg_input_file = os.path.join('neg_feat_vec.csv')
df_pos = pd.read_csv(pos_input_file, header = 0, usecols= range(1,26))
df_neg = pd.read_csv(neg_input_file, header = 0, usecols= range(1,26))

#reading labels from csv files
df_posLabel = pd.read_csv(pos_input_file, header = 0, usecols= [25])
df_negLabel = pd.read_csv(neg_input_file, header = 0, usecols= [25])

df = pd.concat([df_pos,df_neg])
df_label = pd.concat([df_posLabel,df_negLabel])

numpy_array = np.array(df)
label_array = np.array(df_label)

#shuffling the data frames
#from sklearn.utils import shuffle
#numpy_array, label_array = shuffle(numpy_array, label_array, random_state=0)


In [36]:
import random
from numpy.random import permutation
import math

# Randomly shuffle the index of nba.
random_indices = permutation(df.index)
# Set a cutoff for how many items we want in the test set (in this case 1/3 of the items)
test_cutoff = math.floor(len(df)/3)
# Generate the test set by taking the first 1/3 of the randomly shuffled indices.
test = df.loc[random_indices[1:test_cutoff]]
# Generate the train set with the rest of the data.
train = df.loc[random_indices[test_cutoff:]]


C:\Users\nafis\Anaconda2\lib\site-packages\ipykernel\__main__.py:10: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
C:\Users\nafis\Anaconda2\lib\site-packages\ipykernel\__main__.py:12: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [37]:
print df_pos.columns[10]
#np.asarray(numpy_array, dtype=None, order=None)
df.head()

\w-\w_end


num_of_words  total_str_len  avg_word_len  fraction_capitalized  \
0             2             16      8.000000                   1.0   
1             2             19      9.500000                   1.0   
2             3             19      6.333333                   1.0   
3             3             18      6.000000                   1.0   
4             3             17      5.666667                   1.0   

   num_of_non-Eng_words  num_of_digits word(s)_with_uppercase_letters  \
0                     1              6                              F   
1                     1              6                              F   
2                     1              5                              F   
3                     1              5                              F   
4                     1              5                              F   

  starts_with_brand paranthesis )_in_last_word  ...  contains_core_info  \
0                 T           F              F  ...                   F   
1                 T           F              F  ...                   F   
2                 T           F              F  ...                   F   
3                 T           F              F  ...                   F   
4                 T           F              F  ...                   F   

  starts_with_i concatenated_words keywords_downstream is_was_downstream  \
0             F                  F                   F                 F   
1             F                  F                   F                 F   
2             F                  F                   F                 F   
3             F                  F                   F                 F   
4             F                  F                   F                 F   

  (_downstream $_downstream the_upstream ,_or_._after_string label  
0            T            T            T                   F   POS  
1            F            T            T                   F   POS  
2            T            T            T                   F   POS  
3            T            T            T                   F   POS  
4            T            F            T                   F   POS  

[5 rows x 25 columns]

In [38]:
x_columns = []
i=1
for col in df_pos.columns:
    if i!=25:
        x_columns.append(col)
    i=i+1
x_columns

['num_of_words',
 'total_str_len',
 'avg_word_len',
 'fraction_capitalized',
 'num_of_non-Eng_words',
 'num_of_digits',
 'word(s)_with_uppercase_letters',
 'starts_with_brand',
 'paranthesis',
 ')_in_last_word',
 '\\w-\\w_end',
 '\\w-\\w_second',
 '\\d_end',
 'contains_year',
 'contains_inch_info',
 'contains_core_info',
 'starts_with_i',
 'concatenated_words',
 'keywords_downstream',
 'is_was_downstream',
 '(_downstream',
 '$_downstream',
 'the_upstream',
 ',_or_._after_string']

In [39]:
# The columns that we will be making predictions with.
#x_columns = ['age', 'g', 'gs', 'mp', 'fg', 'fga', 'fg.', 'x3p', 'x3pa', 'x3p.', 'x2p', 'x2pa', 'x2p.', 'efg.', 'ft', 'fta', 'ft.', 'orb', 'drb', 'trb', 'ast', 'stl', 'blk', 'tov', 'pf']
# The column that we want to predict.
y_column = ['label']

from sklearn.neighbors import KNeighborsRegressor
# Create the knn model.
# Look at the five closest neighbors.
knn = KNeighborsRegressor(n_neighbors=5)
# Fit the model on the training data.
knn.fit(train[x_columns], train[y_column])
# Make point predictions on the test set using the fit model.
#predictions = knn.predict(test[x_columns])


ValueError: could not convert string to float: F

In [11]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)

array([0, 1, 2])

In [20]:
np.random.seed(0)
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test  = iris_X[indices[-10:]]
iris_y_test  = iris_y[indices[-10:]]
iris_X_test

array([[ 5.6,  3. ,  4.1,  1.3],
       [ 5.9,  3.2,  4.8,  1.8],
       [ 6.3,  2.3,  4.4,  1.3],
       [ 5.5,  3.5,  1.3,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 6.3,  2.9,  5.6,  1.8],
       [ 5.8,  2.7,  4.1,  1. ],
       [ 7.7,  3.8,  6.7,  2.2],
       [ 4.6,  3.2,  1.4,  0.2]])

In [19]:
# Create and fit a nearest-neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train) 
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')
knn.predict(iris_X_test)

array([1, 2, 1, 0, 0, 0, 2, 1, 2, 0])